### ISSUE TITLE
404 error on hitomi

### ISSUE THREAD

**Issue by yant0** [Nonononoki/Hendroid#50]
**Hendroid Version**: 1.15.14

**Device/Android Version**: asus zenfone max pro m1 stock android 9 / works on normal browser

**Issue details / Repro steps**: open hitomi, download
expekted behaviour : download - actual behaviour : downloading @ 2kbps 0/0mb. Have tried restating my phone & deleting app & browser cache

**Stack trace / LogCat**:
```
2021-12-29T06:53:46.327 02 - [Networking] : Server error; HTTP statusCode=404; message=null
```

**Comment by Nonononoki** [comment]
I'm also using Hitomi and have found no such problems. Please post a link of the book that's not downloading

**Comment by yant0** [comment]
Everybook. The first 26 books i downloaded *right after downloading the app* was fine, few hours after not using the app and then i opened the app to download at hitomi again but doesnt work. The webview was very much working, even the gallery webview. Unfortunately i cannot retreat the log since posting this i changed rom

forgot to mention the url on the error is the hitomi gallery (aa.hitomi... wa.hitomi.. etc)

**Comment by yant0** [comment]
im not sure it might be my battery / phone. Ive read that hitomi throws the whole database for you to scan and not the otherway around

**Comment by Nonononoki** [comment]
Have you used the "redownload from scratch" button? I need a link from a book to confirm the issue or else I can't help without logs.

**Comment by dreyfrancisco** [comment]
[orca_share_media1640970434913_6882728859046427263.txt](https://github.com/Nonononoki/Hendroid/files/7796726/orca_share_media1640970434913_6882728859046427263.txt)

im getting the same errors for all hitomi downloads

**Comment by maximumburst** [comment]
[orca_share_media1640970434913_6882728859046427263.txt](https://github.com/Nonononoki/Hendroid/files/7796733/orca_share_media1640970434913_6882728859046427263.txt)

getting similar errors on all of my hitomi downloads

**Comment by Nonononoki** [comment]
Ah, I can now replicate the issue. Issue is known upstream and fixes will be merged when available.

**Comment by maximumburst** [comment]
> Ah, I can now replicate the issue. Issue is known upstream and fixes will be merged when available.

thanks. good luck on fixing it. hope to see it soon

**Comment by Nonononoki** [comment]
Should be fixed now: https://github.com/Nonononoki/Hendroid/releases/tag/1.15.15

**Comment by maximumburst** [comment]
Still getting errors on hitomi
![chrome_screenshot_1641492350649](https://user-images.githubusercontent.com/96921254/148429674-f8992957-3700-47f8-9c4b-8600283a46da.png)

**Comment by Nonononoki** [comment]
@maximumburst Please go to Downloads - Errors - Long tap on the book(s) with errors and press "Redownload from scratch"

**Comment by maximumburst** [comment]
Thanks it worked. But im having troubles with accessing hitomi itself. Everytime i try to open hitomi it just crashes the whole app

**Comment by Nonononoki** [comment]
@maximumburst New release should fix that: https://github.com/Nonononoki/Hendroid/releases/tag/1.15.17
